---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: dotnet-backend
  labels:
    project: dotnet-backend
    role: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend01
    role: backend
    app.kubernetes.io/part-of: "Service-A"
    app.openshift.io/runtime: dotnet
  name: backend01
  namespace: dotnet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend01
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend01
        role: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - backend
      containers:
      - image: quay.io/cvicens/backend01:3.1
        name: backend01
        env:
          - name: BACKEND_HOST
            value: backend01.dotnet-backend
        resources: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend02
    role: backend
    app.kubernetes.io/part-of: "Service-B"
    app.openshift.io/runtime: dotnet
  name: backend02
  namespace: dotnet-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend02
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend02
        role: backend
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                - backend
      containers:
      - image: quay.io/cvicens/backend02:3.1
        name: backend02
        env:
          - name: BACKEND_HOST
            value: backend02.dotnet-backend
        resources: {}
---
kind: Service
apiVersion: v1
metadata:
  name: backend01
  namespace: dotnet-backend
  labels:
    app: backend01
    role: backend
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: backend01
  type: ClusterIP
---
kind: Service
apiVersion: v1
metadata:
  name: backend02
  namespace: dotnet-backend
  labels:
    app: backend02
    role: backend
spec:
  ports:
    - name: 5000-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: backend02
  type: ClusterIP